### PR TITLE
completed css-brochure-form

### PR DESCRIPTION
**Pull request by dcatan89**
Screen Shot 2021-12-01 at 8 42 49 PM

### CODE REVIEW

**Comment by dcatan89** [comment]
Screen Shot 2021-12-01 at 8 48 58 PM

**Comment by dcatan89** [comment]
Screen Shot 2021-12-02 at 9 59 59 AM
Most recent updates

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Daniel! The border style for your inputs is incorrect as compared to the example. Additionally, the color of your header and button doesn't match the example, it is more orange than the example given. Please revise and submit with a new screenshot.

**Comment by dcatan89** [comment]
Screen Shot 2021-12-02 at 3 26 58 PM

**Review by codingcodymiller — APPROVED** [review]
Great work!!

**Pull request merged**
